import { bikeCategories } from "./bike-classification.js";
export const categories = { gravel: "Гравел", road: "Шоссе", ...bikeCategories };
export const models = {
  gravel: {
    Canyon: ["Grizl", "Grail"],
    Specialized: ["Diverge", "Crux"],
    Trek: ["Checkpoint", "Checkmate"],
    Cannondale: ["Topstone"],
    Giant: ["Revolt"],
    Scott: ["Addict Gravel", "Speedster Gravel"],
    Merida: ["Silex"],
    Cube: ["Nuroad"],
    Orbea: ["Terra"],
    BMC: ["URS"],
    "3T": ["Exploro", "Extrema"],
    Cervélo: ["Áspero"],
    Marin: ["Gestalt", "Headlands"],
    Kona: ["Rove", "Libre"],
    Surly: ["Straggler", "Midnight Special"],
  },
  mtb: {
    Canyon: ["Grand Canyon", "Lux", "Neuron", "Spectral"],
    Specialized: ["Rockhopper", "Epic", "Stumpjumper"],
    Trek: ["Marlin", "Procaliber", "Fuel EX"],
    Giant: ["Talon", "XTC", "Trance"],
    Scott: ["Scale", "Spark"],
    Merida: ["Big.Nine", "One-Twenty"],
    Cube: ["Aim", "Reaction", "Stereo"],
    Orbea: ["Alma", "Oiz", "Occam"],
    Cannondale: ["Trail", "Scalpel"],
    "Santa Cruz": ["Chameleon", "Tallboy", "Hightower"],
  },
  road: {
    Canyon: ["Endurace", "Ultimate", "Aeroad"],
    Specialized: ["Allez", "Tarmac", "Roubaix", "Aethos"],
    Trek: ["Domane", "Émonda", "Madone"],
    Giant: ["Contend", "Defy", "TCR", "Propel"],
    Cannondale: ["CAAD13", "SuperSix EVO", "Synapse"],
    Scott: ["Addict", "Foil"],
    Merida: ["Scultura", "Reacto"],
    Orbea: ["Orca", "Avant"],
    BMC: ["Teammachine", "Roadmachine"],
    Cervélo: ["Caledonia", "R5", "S5"],
    "3T": ["Strada"],
  },
};
export const partCategories = {
  build: [
    "Рама",
    "Вилка",
    "Амортизатор",
    "Групсет",
    "Задний переключатель",
    "Передний переключатель",
    "Манетки / дуалы",
    "Система / шатуны",
    "Каретка",
    "Кассета",
    "Цепь",
    "Тормоза",
    "Роторы",
    "Колёса",
    "Втулки",
    "Покрышки",
    "Камеры / бескамерка",
    "Руль",
    "Вынос",
    "Рулевая",
    "Подседельный штырь",
    "Седло",
    "Грипсы / обмотка",
    "Педали",
    "Другое",
  ],
  accessories: [
    "Велокомпьютер",
    "Датчики",
    "Передний свет",
    "Задний свет",
    "Подседельная сумка",
    "Рамная сумка",
    "Сумка на руль",
    "Багажник",
    "Крылья",
    "Фляга / держатель",
    "Насос",
    "Инструменты",
    "Замок",
    "Звонок",
    "Другое",
  ],
};
export const parts = {
  Групсет: [
    "Shimano GRX RX820",
    "Shimano GRX RX600",
    "Shimano DEORE XT",
    "Shimano DEORE",
    "Shimano SLX",
    "Shimano XTR",
    "Shimano 105",
    "Shimano Ultegra",
    "Shimano Dura-Ace",
    "SRAM Apex",
    "SRAM Rival AXS",
    "SRAM Force AXS",
    "SRAM Red AXS",
    "SRAM GX Eagle",
    "SRAM XX Eagle",
    "Campagnolo Ekar",
    "Campagnolo Super Record",
  ],
  "Задний переключатель": [
    "Shimano XT RD-M8100",
    "Shimano GRX RD-RX820",
    "Shimano GRX RD-RX822",
    "Shimano 105 RD-R7100",
    "SRAM GX Eagle",
    "SRAM Rival XPLR AXS",
  ],
  "Передний переключатель": [
    "Shimano GRX FD-RX820",
    "Shimano 105 FD-R7100",
    "Shimano Ultegra FD-R8000",
  ],
  "Манетки / дуалы": [
    "Shimano GRX ST-RX820",
    "Shimano 105 ST-R7120",
    "Shimano XT SL-M8100",
    "SRAM Rival AXS",
  ],
  "Система / шатуны": [
    "Shimano GRX FC-RX820",
    "Shimano XT FC-M8100",
    "Shimano 105 FC-R7100",
    "SRAM GX Eagle",
  ],
  Каретка: ["Shimano BB-MT800", "Shimano SM-BBR60", "SRAM DUB"],
  Кассета: [
    "Shimano XT CS-M8100 10–51T",
    "Shimano CS-HG710 11–36T",
    "SRAM XG-1275 10–52T",
  ],
  Цепь: ["Shimano CN-M8100", "Shimano CN-M7100", "SRAM GX Eagle", "KMC X12"],
  Тормоза: [
    "Shimano XT BR-M8100",
    "Shimano XT BR-M8120",
    "Shimano GRX BR-RX820",
    "Shimano 105 BR-R7170",
    "SRAM Code R",
    "SRAM Level",
    "Magura MT5",
    "TRP Spyre",
  ],
  Роторы: ["Shimano RT-MT800", "Shimano SM-RT70", "SRAM CenterLine"],
  Колёса: [
    "DT Swiss G 1800 SPLINE",
    "DT Swiss GR 1600 SPLINE",
    "DT Swiss ER 1600 SPLINE",
    "DT Swiss X 1900 SPLINE",
    "Mavic Allroad",
    "Zipp 303 S",
    "Hunt 4 Season Gravel",
    "Fulcrum Rapid Red",
  ],
  Втулки: ["DT Swiss 350", "DT Swiss 240", "Hope Pro 5"],
  Покрышки: [
    "Continental Terra Speed",
    "Continental Grand Prix 5000",
    "Continental Race King",
    "Schwalbe G-One Allround",
    "Schwalbe G-One Bite",
    "Schwalbe Racing Ralph",
    "Maxxis Ikon",
    "Maxxis Ardent",
    "Maxxis Minion DHF",
    "Vittoria Corsa",
    "Panaracer GravelKing SK",
    "WTB Riddler",
  ],
  Руль: [
    "Ritchey VentureMax",
    "Ritchey WCS Butano",
    "Zipp Service Course SL-70 XPLR",
    "PRO Discover",
    "Race Face Chester",
    "Renthal Fatbar",
  ],
  Вынос: [
    "Ritchey WCS C220",
    "Zipp Service Course",
    "PRO Discover",
    "Race Face Turbine",
  ],
  "Подседельный штырь": [
    "Thomson Elite",
    "Ritchey WCS",
    "RockShox Reverb",
    "OneUp Dropper Post",
  ],
  Седло: [
    "Brooks C17",
    "Brooks C17 Carved",
    "Brooks B17",
    "Fizik Terra Argo X5",
    "Fizik Vento Argo",
    "Selle Italia SLR",
    "Selle Italia Model X",
    "Ergon SM Pro",
    "Specialized Power",
  ],
  "Грипсы / обмотка": [
    "Brooks Cambium Rubber Grips",
    "Brooks Microfibre Bar Tape",
    "Ergon GA3",
    "Ergon GP1",
    "ESI Chunky",
    "Lizard Skins DSP",
    "Supacaz Super Sticky Kush",
  ],
  Педали: [
    "Shimano XT PD-M8100",
    "Shimano PD-M520",
    "Shimano PD-EH500",
    "Crankbrothers Stamp 1",
    "Look Keo 2 Max",
    "Race Face Chester",
  ],
  Вилка: [
    "RockShox SID",
    "RockShox Reba",
    "RockShox Pike",
    "FOX 32",
    "FOX 34",
    "FOX 36",
  ],
  Амортизатор: ["RockShox Deluxe", "RockShox Super Deluxe", "FOX Float"],
  Велокомпьютер: [
    "Garmin Edge 540",
    "Garmin Edge 840",
    "Garmin Edge 1040",
    "Wahoo ELEMNT BOLT",
    "Wahoo ELEMNT ROAM",
    "Hammerhead Karoo",
    "Bryton Rider 750",
  ],
  Датчики: [
    "Garmin Speed Sensor 2",
    "Garmin Cadence Sensor 2",
    "Wahoo RPM Cadence",
  ],
  "Передний свет": [
    "Lezyne Lite Drive 1000XL",
    "Lezyne Macro Drive",
    "Cateye AMPP800",
    "Fenix BC30",
  ],
  "Задний свет": [
    "Garmin Varia RTL515",
    "Lezyne Strip Drive",
    "Knog Blinder",
    "Cateye Rapid X",
  ],
  "Подседельная сумка": [
    "Apidura Expedition Saddle Pack",
    "Ortlieb Seat-Pack",
    "Topeak BackLoader",
  ],
  "Рамная сумка": [
    "Apidura Expedition Frame Pack",
    "Ortlieb Frame-Pack",
    "Topeak MidLoader",
  ],
  "Сумка на руль": [
    "Ortlieb Handlebar-Pack",
    "Apidura Expedition Handlebar Pack",
    "Topeak FrontLoader",
  ],
  Багажник: ["Tubus Logo", "Ortlieb Quick-Rack"],
  Крылья: ["SKS Bluemels", "SKS Speedrocker"],
  "Фляга / держатель": [
    "Elite Custom Race Plus",
    "Elite Fly",
    "CamelBak Podium",
    "Topeak Modula Cage",
  ],
  Насос: ["Lezyne Pocket Drive", "Topeak RaceRocket", "Crankbrothers Gem"],
  Инструменты: ["Crankbrothers M19", "Topeak Mini 20 Pro"],
  Замок: ["ABUS Bordo", "Kryptonite Evolution"],
  Звонок: ["Knog Oi"],
};
export const manufacturers = [
  "Shimano",
  "SRAM",
  "Campagnolo",
  "Brooks",
  "Fizik",
  "Selle Italia",
  "Ergon",
  "Ritchey",
  "PRO",
  "Zipp",
  "DT Swiss",
  "Mavic",
  "Fulcrum",
  "Hunt",
  "Continental",
  "Schwalbe",
  "Maxxis",
  "Vittoria",
  "Panaracer",
  "WTB",
  "RockShox",
  "FOX",
  "Race Face",
  "Hope",
  "Magura",
  "TRP",
  "Garmin",
  "Wahoo",
  "Hammerhead",
  "Bryton",
  "Lezyne",
  "Cateye",
  "Knog",
  "Fenix",
  "Apidura",
  "Ortlieb",
  "Topeak",
  "SKS",
  "Elite",
  "CamelBak",
  "Crankbrothers",
  "Look",
  "KMC",
  "ABUS",
  "Kryptonite",
];
