export const fontLabels = {
  manrope: "Manrope",
  inter: "Inter",
  roboto: "Roboto",
  opensans: "Open Sans",
  sourcesans3: "Source Sans 3",
  notosans: "Noto Sans",
  montserrat: "Montserrat",
  rubik: "Rubik",
  onest: "Onest",
  golostext: "Golos Text",
  system: "Системный",
  arial: "Arial",
  georgia: "Georgia",
  mono: "Моноширинный",
};
export const fontNames = Object.keys(fontLabels);
export const hostedFonts = [
  "manrope",
  "inter",
  "roboto",
  "opensans",
  "sourcesans3",
  "notosans",
  "montserrat",
  "rubik",
  "onest",
  "golostext",
];
export const fontStacks = {
  manrope: '"Cola Manrope", system-ui, sans-serif',
  inter: '"Cola Inter", system-ui, sans-serif',
  roboto: '"Cola Roboto", system-ui, sans-serif',
  opensans: '"Cola Open Sans", system-ui, sans-serif',
  sourcesans3: '"Cola Source Sans 3", system-ui, sans-serif',
  notosans: '"Cola Noto Sans", system-ui, sans-serif',
  montserrat: '"Cola Montserrat", system-ui, sans-serif',
  rubik: '"Cola Rubik", system-ui, sans-serif',
  onest: '"Cola Onest", system-ui, sans-serif',
  golostext: '"Cola Golos Text", system-ui, sans-serif',
  system:
    'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  arial: "Arial, Helvetica, sans-serif",
  georgia: 'Georgia, "Times New Roman", serif',
  mono: '"Courier New", monospace',
};
