// The catalog of verified metrics for awards and records (#106). The values
// come from SQL functions in db/027_game_rules.sql (awards, ride and person
// records) and from the bike snapshot in lib/gamification.js (bike records);
// an administrator combines these metrics into rules and never writes SQL.
// Client-safe: no database imports.

/**
 * @typedef {'bike'|'ride'|'user'} MetricSubject
 * @typedef {'category'|'minDistanceKm'|'keywords'} MetricFilter
 * @typedef {{key:string,label:string,unit:string,subject:MetricSubject,group:string,award:boolean,record:boolean,filters:MetricFilter[],max:number,step:number,reactions?:boolean}} GameMetric
 */

export const metricGroups = Object.freeze([
  { id: "price", name: "Стоимость" },
  { id: "weight", name: "Вес" },
  { id: "bike", name: "Велосипед" },
  { id: "build", name: "Комплектация" },
  { id: "rides", name: "Покатушки" },
  { id: "journal", name: "Журнал" },
  { id: "community", name: "Признание сообщества" },
]);

/** @type {ReadonlyArray<GameMetric>} */
export const gameMetrics = Object.freeze([
  // A bike: records rank public bikes of the rating; awards go to a bike.
  {
    key: "price",
    label: "Цена велосипеда (если владелец её показывает)",
    unit: "₽",
    subject: "bike",
    group: "price",
    award: false,
    record: true,
    filters: ["category"],
    max: 1e9,
    step: 1,
  },
  {
    key: "weight",
    label: "Вес велосипеда",
    unit: "кг",
    subject: "bike",
    group: "weight",
    award: false,
    record: true,
    filters: ["category"],
    max: 200,
    step: 0.1,
  },
  {
    key: "year",
    label: "Модельный год",
    unit: "",
    subject: "bike",
    group: "bike",
    award: false,
    record: true,
    filters: ["category"],
    max: 2100,
    step: 1,
  },
  {
    key: "keywords",
    label: "Детали с ключевыми словами в названии",
    unit: "шт.",
    subject: "bike",
    group: "bike",
    award: true,
    record: false,
    filters: ["category", "keywords"],
    max: 100,
    step: 1,
  },
  {
    key: "build_parts",
    label: "Детали комплектации у велосипеда с фото",
    unit: "шт.",
    subject: "bike",
    group: "build",
    award: true,
    record: false,
    filters: ["category"],
    max: 500,
    step: 1,
  },
  {
    key: "completeness",
    label: "Заполненность карточки",
    unit: "%",
    subject: "bike",
    group: "build",
    award: false,
    record: true,
    filters: ["category"],
    max: 100,
    step: 1,
  },
  {
    key: "upgrade",
    label: "Прокаченность сборки",
    unit: "%",
    subject: "bike",
    group: "build",
    award: false,
    record: true,
    filters: ["category"],
    max: 100,
    step: 1,
  },
  {
    key: "likes",
    label: "Лайки велосипеда",
    unit: "",
    subject: "bike",
    group: "community",
    award: true,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
  },
  {
    key: "wild",
    label: "Реакции «Безумие»",
    unit: "",
    subject: "bike",
    group: "community",
    award: false,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
    reactions: true,
  },
  {
    key: "clean",
    label: "Реакции «Чистая сборка»",
    unit: "",
    subject: "bike",
    group: "community",
    award: false,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
    reactions: true,
  },
  {
    key: "dream",
    label: "Реакции «Хочу такой»",
    unit: "",
    subject: "bike",
    group: "community",
    award: false,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
    reactions: true,
  },
  {
    key: "community",
    label: "Участники с дополнительными реакциями",
    unit: "",
    subject: "bike",
    group: "community",
    award: false,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
    reactions: true,
  },
  // A ride: public rides on public bikes; an award goes to the rider.
  {
    key: "ride_distance",
    label: "Дистанция покатушки",
    unit: "км",
    subject: "ride",
    group: "rides",
    award: true,
    record: true,
    filters: ["category", "minDistanceKm"],
    max: 10000,
    step: 0.1,
  },
  {
    key: "ride_elevation",
    label: "Набор высоты за покатушку",
    unit: "м",
    subject: "ride",
    group: "rides",
    award: true,
    record: true,
    filters: ["category", "minDistanceKm"],
    max: 100000,
    step: 1,
  },
  {
    key: "ride_avg_speed",
    label: "Средняя скорость покатушки",
    unit: "км/ч",
    subject: "ride",
    group: "rides",
    award: true,
    record: true,
    filters: ["category", "minDistanceKm"],
    max: 200,
    step: 0.1,
  },
  {
    key: "ride_max_speed",
    label: "Максимальная скорость (если владелец её показывает)",
    unit: "км/ч",
    subject: "ride",
    group: "rides",
    award: true,
    record: true,
    filters: ["category", "minDistanceKm"],
    max: 300,
    step: 0.1,
  },
  // A person: only public activity counts.
  {
    key: "rides_count",
    label: "Число покатушек",
    unit: "",
    subject: "user",
    group: "rides",
    award: true,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
  },
  {
    key: "distance_30d",
    label: "Километры за последние 30 дней",
    unit: "км",
    subject: "user",
    group: "rides",
    award: true,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
  },
  {
    key: "months_in_year",
    label: "Месяцы с покатушками в одном календарном году",
    unit: "",
    subject: "user",
    group: "rides",
    award: true,
    record: false,
    filters: ["category"],
    max: 12,
    step: 1,
  },
  {
    key: "journal_entries",
    label: "Записи журнала",
    unit: "",
    subject: "user",
    group: "journal",
    award: true,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
  },
  {
    key: "service_entries",
    label: "Записи об обслуживании",
    unit: "",
    subject: "user",
    group: "journal",
    award: true,
    record: true,
    filters: ["category"],
    max: 1e6,
    step: 1,
  },
  {
    key: "public_bikes",
    label: "Публичные велосипеды",
    unit: "",
    subject: "user",
    group: "bike",
    award: true,
    record: false,
    filters: ["category"],
    max: 1000,
    step: 1,
  },
  {
    key: "categories",
    label: "Категории публичных велосипедов",
    unit: "",
    subject: "user",
    group: "bike",
    award: true,
    record: false,
    filters: [],
    max: 20,
    step: 1,
  },
  {
    key: "owner_likes",
    label: "Лайки всех велосипедов владельца",
    unit: "",
    subject: "user",
    group: "community",
    award: true,
    record: false,
    filters: [],
    max: 1e7,
    step: 1,
  },
  {
    key: "followers",
    label: "Подписчики",
    unit: "",
    subject: "user",
    group: "community",
    award: true,
    record: true,
    filters: [],
    max: 1e7,
    step: 1,
  },
  {
    key: "discussions",
    label: "Обсуждения чужих велосипедов",
    unit: "",
    subject: "user",
    group: "community",
    award: true,
    record: false,
    filters: [],
    max: 1e6,
    step: 1,
  },
]);

export const metricByKey = Object.freeze(
  Object.fromEntries(gameMetrics.map((m) => [m.key, m])),
);

// A number with its unit: "12,3 км", "85 %", "250 000 ₽".
export function metricValue(metricKey, value) {
  const metric = metricByKey[metricKey];
  if (value == null || !metric) return "";
  const number = new Intl.NumberFormat("ru-RU", {
    maximumFractionDigits: metric.step < 1 ? 2 : 0,
    // A year reads 1998, not "1 998".
    useGrouping: metricKey !== "year",
  }).format(Number(value));
  if (!metric.unit) return number;
  return metric.unit === "%" ? number + "%" : number + " " + metric.unit;
}
