import { defaultEmojis, defaultArticleTopics } from "./ui-emoji.ts";
import type { SiteSettings, SiteCatalog } from "./contracts.ts";
import {
  appearanceDefaults,
  heroDefaults,
  backgroundDefaults,
} from "./theme.ts";
import { mapDefaults } from "./map-settings.ts";
import { aboutDefaults } from "./about-content.ts";
import { defaultScoring } from "./bike-score.ts";
import { defaultGroups, defaultBlocks } from "./garage-layout.ts";
import {
  categories,
  models,
  parts,
  partCategories,
  manufacturers,
} from "./catalog.ts";
export const defaultSettings: SiteSettings = {
  emojis: defaultEmojis,
  iconColors: {},
  menuOpenOnHover: true,
  autoScrollSpeed: 24,
  brandLogoId: null,
  componentIllustrations: { groups: {}, categories: {} },
  graphicsCreditsLabel: "Авторы графики",
  graphicsCreditsUrl: "",
  articleTopics: defaultArticleTopics,
  appearance: appearanceDefaults,
  ...heroDefaults,
  ...backgroundDefaults,
  showAboutStats: true,
  about: aboutDefaults,
  map: mapDefaults,
  rideListMode: "auto",
  rideMapView: "map",
  mapScrollZoom: false,
  aboutGuideImageId: null,
  aboutTechnologyImageId: null,
  authImageId: null,
  authRegisterImageId: null,
  footerImage1Id: null,
  footerImage2Id: null,
  footerImage3Id: null,
  footerImage4Id: null,
  footerLink1: "",
  footerLink2: "",
  footerLink3: "",
  footerLink4: "",
  scoring: defaultScoring,
  bikeLayout: "balanced",
  showMileage: false,
  componentsExpanded: false,
  appVersionLabel: "",
  parserVersionLabel: "",
  mtbImageId: null,
  roadImageId: null,
  gravelImageId: null,
  summaryPosition: "right",
  detailOrder: "photo-first",
  photoMode: "natural",
  photoRatio: "4/3",
  textAlign: "left",
  desktopColumns: 3,
  showTagline: true,
  showDemo: true,
  registrationOpen: true,
  // How long a published market listing stays on the market (#116).
  marketListingDays: 60,
  siteName: "ColaBike",
  showcaseTitle: "Наши велосипеды",
  siteDescription: "Витрина велосипедов, комплектаций и авторских сборок.",
  faviconId: null,
  demoImageId: null,
  wizardLinkLabel: "Распознать по странице магазина",
  wizardManualLabel: "Заполнить вручную",
  copy: {},
  detailBlocks: defaultBlocks,
  summaryFields: {
    description: true,
    metadata: true,
    manufacturer: true,
    price: true,
  },
};
import { defaultPurposes, defaultAliases } from "./experience-catalog.ts";
export const defaultCatalog: SiteCatalog = {
  purposes: defaultPurposes,
  aliases: defaultAliases,
  sizes: ["XS", "S", "M", "L", "XL"],
  categories,
  models,
  parts,
  partCategories,
  manufacturers,
  icons: {},
  componentGroups: defaultGroups,
};
