export const uiIconNames = [
  "ArrowLeft",
  "ArrowUpRight",
  "Bell",
  "Bike",
  "BookOpen",
  "Calendar",
  "Camera",
  "Check",
  "CheckCheck",
  "ChevronDown",
  "ChevronRight",
  "ChevronUp",
  "Code2",
  "Copy",
  "ExternalLink",
  "Flag",
  "Flame",
  "Gauge",
  "Globe",
  "Heart",
  "History",
  "Home",
  "Image",
  "Info",
  "Layers",
  "Link",
  "LoaderCircle",
  "Lock",
  "LogOut",
  "MapPin",
  "Medal",
  "Menu",
  "MessageCircle",
  "Package",
  "Palette",
  "Pencil",
  "Plus",
  "RefreshCw",
  "RotateCcw",
  "Route",
  "Save",
  "ScanLine",
  "Search",
  "Settings2",
  "Shield",
  "ShieldCheck",
  "SlidersHorizontal",
  "Sparkles",
  "Star",
  "Trash2",
  "TriangleAlert",
  "Trophy",
  "Type",
  "Upload",
  "UserRound",
  "Users",
  "X",
  "Zap",
  "NotebookPen",
];
export const uiIconLabels = {
  Bike: "Велосипед",
  NotebookPen: "Журнал",
  Route: "Покатушка",
  Heart: "Лайк",
  MessageCircle: "Комментарии",
  Search: "Поиск",
  SlidersHorizontal: "Фильтры",
  Trophy: "Рекорды",
  Medal: "Награда",
  CheckCheck: "Заполненность",
  Zap: "Прокаченность",
  Users: "Участники",
  Bell: "Уведомления",
  Menu: "Мобильное меню",
  Info: "О проекте",
  Plus: "Добавить",
  Pencil: "Редактировать",
  Trash2: "Удалить",
  Camera: "Нет фотографии",
  LogOut: "Выйти",
  Shield: "Админка",
  UserRound: "Профиль",
  Upload: "Загрузить",
  Image: "Изображение",
  Settings: "Настройки",
  Settings2: "Настройки",
  ArrowUpRight: "Перейти",
  ChevronDown: "Раскрыть",
  ChevronUp: "Свернуть",
  ChevronLeft: "Назад",
  ChevronRight: "Вперёд",
  X: "Закрыть",
  Home: "Витрина",
  Lock: "Приватность",
  Globe: "Публичность",
  Flag: "Жалоба",
  Save: "Сохранить",
  RotateCcw: "Сбросить",
  CalendarDays: "Дата",
  Gauge: "Показатели",
  Wrench: "Обслуживание",
  BookOpen: "Справка",
};
