import {
  Bell,
  Bike,
  Bookmark,
  Building2,
  Calendar,
  CalendarPlus,
  Check,
  CircleHelp,
  Compass,
  Download,
  Flame,
  Heart,
  Home,
  Info,
  Library,
  LogOut,
  Menu,
  Monitor,
  Moon,
  Mountain,
  NotebookPen,
  Package,
  PenLine,
  Plus,
  Repeat,
  RotateCcw,
  Route,
  Ruler,
  Scale,
  Search,
  Settings2,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trees,
  Trophy,
  UserRound,
  Users,
  X,
} from "./icons.jsx";
// One line icon set for navigation, menus and buttons (#104): fixed, not
// configurable, stroke 2. Names are the former emoji slots and bike categories.
const icons = {
  home: Home,
  bike: Bike,
  journal: NotebookPen,
  articles: Library,
  rides: Compass,
  market: ShoppingBag,
  about: Info,
  profile: UserRound,
  notifications: Bell,
  subscriptions: Users,
  saved: Bookmark,
  records: Trophy,
  admin: Settings2,
  logout: LogOut,
  search: Search,
  menu: Menu,
  light: Sun,
  dark: Moon,
  system: Monitor,
  add: Plus,
  addBike: Bike,
  addRide: Route,
  plan: CalendarPlus,
  import: Download,
  write: PenLine,
  new: Sparkles,
  popular: Flame,
  filters: SlidersHorizontal,
  heart: Heart,
  size: Ruler,
  weight: Scale,
  date: Calendar,
  yes: Check,
  no: X,
  maybe: CircleHelp,
  repeat: Repeat,
  reset: RotateCcw,
  apply: Check,
  mtb: Mountain,
  road: Route,
  gravel: Trees,
  road_gravel: Route,
  urban_touring: Building2,
  bmx: Bike,
  cargo_utility: Package,
  special: Sparkles,
};
export default function SiteIcon({ name, size = 18, className = "" }) {
  const Icon = icons[name] || Plus;
  return (
    <Icon
      size={size}
      strokeWidth={2}
      className={"site-icon " + className}
      aria-hidden="true"
    />
  );
}
