import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
const hash = createHash("sha256");
async function walk(dir) {
  for (const e of (await readdir(dir, { withFileTypes: true })).sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const p = dir + "/" + e.name;
    if (e.isDirectory()) await walk(p);
    else if (!p.endsWith("/version.js"))
      hash.update(p).update(await readFile(p));
  }
}
for (const p of ["app", "lib", "db"]) await walk(p);
const { version } = JSON.parse(await readFile("package.json", "utf8"));
await writeFile(
  "lib/version.js",
  "// Generated by build-version.js\nexport const appVersion = " +
    JSON.stringify({ version, build: hash.digest("hex").slice(0, 10) }) +
    ";\n",
);
